///////////////////////////////////////////////////////////////////////////////
// CppElbowControlInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "CppElbowControlServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
