///////////////////////////////////////////////////////////////////////////////
// CppElbowControlClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "CppElbowControlClassFactory.h"
#include "CppElbowControlServices.h"
#include "CppElbowControlVersion.h"
#include "Module1.h"

BEGIN_CLASS_MAP(CCppElbowControlClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_CppElbowControlCModule1, SRVNAME_CPPELBOWCONTROL "!CModule1", CModule1)
///</AutoGeneratedContent>
END_CLASS_MAP()

CCppElbowControlClassFactory::CCppElbowControlClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_CPPELBOWCONTROL)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(CppElbowControl));
#endif //defined(TCDBG_UNIT_VERSION)
}

