///////////////////////////////////////////////////////////////////////////////
// CppElbowControlServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_CppElbowControl = 0x3F000000;
#define SRVNAME_CPPELBOWCONTROL "CppElbowControl"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_CppElbowControlCModule1 = {0xa039ffa3,0xdba9,0x4f0e,{0x8c,0x4f,0x4c,0x51,0x21,0x05,0x3e,0x4b}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1Parameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Parameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Module1Parameter, *PModule1Parameter;

typedef struct _Module1Inputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
	float Angle;
	float PlcTimer;
} Module1Inputs, *PModule1Inputs;

#pragma pack(push,1)
typedef struct _Module1Outputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
	SHORT m1Int;
	SHORT m2Int;
	SHORT m3Int;
} Module1Outputs, *PModule1Outputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
